### ISSUE TITLE
Enable Support for phpMyAdmin

### ISSUE THREAD

**Issue by collizo4sky** [wplib/wplib-box#117]
I installed phpmyadmin at www folder. Accessing wplib.box/phpmyadmin resulted in

```
The wplib.box page isn’t working

wplib.box is currently unable to handle this request.
```

**Comment by collizo4sky** [comment]
cc @mikeschinkel

**Comment by mikeschinkel** [comment]
@collizo4sky Will Adminer work for you instead?   Have you considered downloading Sequel Pro?

We can get PhpMyAdmin working but both of those are better options...

**Comment by collizo4sky** [comment]
Am used to phpmyadmin.

Already downloaded and using sequel pro but i still desire phpmyadmin

**Comment by mikeschinkel** [comment]
I will install PhpMyAdmin later today and see if I run into the same issue.

**Comment by mikeschinkel** [comment]
@collizo4sky I just tried to install PhpMyAdmin and ran into a whole bunch of different issues, some of which I am concerned would cause the rest of the box to be unstable so I decided to stop. 

Note I was trying to install on top of our existing box image in order to provide a tutorial for how to install it, I was not working with the box image itself, which I do not work on _(@clubdeuce does.)_

How difficult  for you it is to learn a new _(and IMO a better) tool in [Sequel Pro](http://www.sequelpro.com/)?  Is sticking with PhpMyAdmin really that important?

However I will talk with @clubdeuce and see what the options we might have to make it work. Unfortunately given client projects we may not be able to discuss immediately.

**Comment by collizo4sky** [comment]
Its alright. Take your time.

FWIW, i have temporarily switch to laravel homestead and successfully running phpMyAdmin.

**Comment by mikeschinkel** [comment]
> i have temporarily switch to laravel homestead 

:-(

**Comment by collizo4sky** [comment]
No way to get phpmyadmin working was a bummer for me.

Call me old school. I have grown accustom to it for my database management.

**Comment by mikeschinkel** [comment]
Not saying it won't happen.  We just have to discuss what it will take.  It might be easy for @clubdeuce.

**Comment by collizo4sky** [comment]
I could get it to work by creating a new project for it. Nut that would mean only getting it working with my wordpress dev box inactive.

Unlike 
homestead, you can only create one site per box instance/project. This was the limiting factor.

**Comment by mikeschinkel** [comment]
> I could get it to work by creating a new project for it. Nut that would mean only getting it working with my wordpress dev box inactive.

I do not understand.   

> You can only create one site per box instance/project.

You can create as many projects as you want with WPLib Box.  Currently that means updating the nginx conf files yourself though but we plan to change that with [our API](/wplib/wplib-box/issues/113) and then our admin console  [our API](/wplib/wplib-box/issues/115).  

And it also means adding alias hostnames in the `Vagrantfile` like this:

     config.hostsupdater.aliases = ["phpmyadmin.wplib.box"]`

**Comment by collizo4sky** [comment]
> I could get it to work by creating a new project for it. But that would mean only getting it working with my wordpress dev box inactive.
> I do not understand what you mean here.

My point was, i could get it to work if i make phpmyadmin a project on it own to have a url like `phpmyadmin.box`

**Comment by mikeschinkel** [comment]
> _My point was, i could get it to work if i make phpmyadmin a project on it own to have a url like phpmyadmin.box_

That is one way.  But you can add more hostnames to WPLib if you want.  

But let's table this until we see if we can add to the box, or provide [an installer for the box](/wplib/wplib-box/issues/118).

**Comment by mikeschinkel** [comment]
@clubdeuce #117 is what _( in part?)_ was need to get PhpMyAdmin working.

**Comment by collizo4sky** [comment]
From the FAQ, apparently adminer (a phpmyadmin alternative) has been added to the box. Any love for phpmyadmin anytime soon?

**Comment by mikeschinkel** [comment]
@collizo4sky We actually discussed adding Adminer about 3 weeks ago and added it 16 days ago. But we just now got it documented.

@clubdeuce and I have periodic calls to discuss what to include in the next release -- about every 2-3 weeks if the past few months are predictive -- and we had met just before you submitted this ticket to set the objectives for the next release. So it may be a bit longer before we will meet to discuss adding this.

BTW, the goal for the next release is to get a functioning API working in the box, which is a decent size project in itself.

One thing I have been thinking about is to come up with a way to support some sort of _"optional packages"_ that we or anyone can build and then easily add to the box. I am envisioning they would be added during the Vagrant _"provisioning"_ step but in a way not likely to fail like typical box provisioning can fail. And also it would need to be very fast to install so that provisioning would not be a long drawn-out process like VVV.

If we added phpMyAdmin as our first _"optional package"_ would that work for you? You'd need to specify it in your `Vagrantfile` or a `.json` file rather than having it be added to the base box image.

**Comment by collizo4sky** [comment]
That should work. I am sure thee are also a number of folks that prefer
phpMyAdmin.

**Comment by mikeschinkel** [comment]
@collizo4sky We got it working.

Be sure to download the latest box image first from your host computer's command line:

    box vagrant update

Then:

    vagrant ssh
    sudo apt-get install php5.6-mcrypt
    sudo apt-get install php-gettext

    # After running the next line follow the instructions "Installing phpMyAdmin" below
    sudo apt-get install phpmyadmin 
   
    sudo service php5.6-fpm restart
    ln -s /usr/share/phpmyadmin /var/www/phpmyadmin

After the above phpMyAdmin should be installed in your WPLib Box.

**Loading phpMyAdmin in your Browser**
You should be able to load phpMyAdmin in your browser at:

- http://wplib.box/phpmyadmin/

You can then use `wordpress` and `wordpress` for username and password, respectively.

If you have changed the hostname of the box, use your new hostname instead of `wplib.box`.

**PHP 7.0**
To also get it working for PHP 7.0 add these commands:

    sudo apt-get install php7.0-mcrypt
    sudo service php7.0-fpm restart

**Installing phpMyAdmin**

1. After running ` sudo apt-get install phpmyadmin` it will run a bit and then display a dialog where it asks you to select Apache or LightHTTP. Just press `<tab>` to select `<Ok>` and press enter.
2. Since Apache is not installed you will have to wait for it to time out.
3. Next you will get a dialog with the heading _"Configuring phpmyadmin"; press enter on with `<Yes>` selected.
4. Finally will be a dialog asking for the root database password. Since there is not root password just press `<tab>` then press enter to select `<Ok>`.
5. That's it. 


Let me know if you have

**Comment by collizo4sky** [comment]
Will give it a spin by Monday and met you know how it shake out.

Thanks for all the hard work.

**Comment by clubdeuce** [comment]
@collizo4sky Were you able to get phpMyAdmin working?

**Comment by collizo4sky** [comment]
Haven't have the time yet. School has resumed and it's been pretty hectic.
I'll see how this weekend shakes out if there will be free time.

On another note, been pretty impressed with Laravel Homestead, spinning up
a site is as easy as editing a Homestead.yaml file.

**Comment by mikeschinkel** [comment]
#295 duplicates this

**Comment by MickMake** [comment]
#295 is closed.
