### ISSUE TITLE
Upgrade MySQL

### ISSUE THREAD

**Issue by nonameolsson** [wplib/wplib-box#149]
The current setup uses MySQL 5.5. This triggers a warning in WordPress. The minimum requirements to run WordPress is MySQL 5.6. 
[https://wordpress.org/about/requirements/](https://wordpress.org/about/requirements/)

The upgrade to MySQL 5.6 should be done in the Vagrant configuration. Each user can ssh into the box and perform a local upgrade, but this wouldn't be the correct way.

**Comment by mikeschinkel** [comment]
Hi @nonameolsson - That is a bit weird.  What indications do you have that we are running 5.5?  

We have installed [5.6 and 7.0](https://github.com/wplib/wplib-box#services--software-included) and I just submitted a feature request (#146) to switch to PHP 7.0 as the default.

What evidence do you have the WPLib Box is running PHP 5.5?

**Comment by nonameolsson** [comment]
Hi @mikeschinkel!
The PHP versions are indeed 5.6 and 7.0. I was talking about `MySQL` :)

**Comment by mikeschinkel** [comment]
@nonameolsson Ah, doh.  I am not gotten enough sleep lately...

We have been discussing possibly switching to MariaDB.  Thoughts?

**Comment by nonameolsson** [comment]
I've never used MariaDB. If I would use MariaDB in development, but MySQL in production, would it be any problems? 

I think that it's nice that you have included both PHP 5.6 and 7.0 with instructions how to change version. Maybe the same approach for MySQL/MariaDB would be a good fit?

**Comment by mikeschinkel** [comment]
> _ If I would use MariaDB in development, but MySQL in production, would it be any problems?_

MariaDB is supposed to be a drop-in replacement. It it from the developers who created MySQL after Sun then Oracle bought MySQL.  I had someone else on our Slack say the following:

> _2) MariaDB. Reading your Github repo, I understand why you've chosen MySQL initially and not to support both. However, this may be an ignorant way of looking at it so hopefully this comes across correctly. It was my understanding that pretty much anyone who's using these sorts of tools will be using MariaDB 9 times out of 10. I'm most likely wrong but thought I'd throw it out there!_

I hope he does not mind me tagging him to bring him into this discussion: @dsgnr.

> _I think that it's nice that you have included both PHP 5.6 and 7.0 with instructions how to change version. Maybe the same approach for MySQL/MariaDB would be a good fit?_

Well, I was thinking that on #136 but @clubdeuce argued against it.  Maybe you want to visit #136 and let make your two cents known?

BTW, I literally just used [Box CLI](https://github.com/wplib/box-cli) which is very much still pre-alpha but you might be interested in checking it out to see where it is headed and to see if there are any commands you could use, or command suggestions you could offer.

**Comment by nonameolsson** [comment]
After reading your quotes I think that I would like to start to use MariaDB. Also found this article [
10 reasons to migrate to MariaDB (if still using MySQL)](https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql).

I do think the suggestion of some kind of "Package Installation" would be balanced way to continue offering a good Vagrant machine for WordPress-development. As someone @mikeschinkel said in https://github.com/wplib/wplib-box/issues/136#issuecomment-234421556: 

> Some people will want to mirror their deployment so won't use our box.

I think that one of the biggest advantages of using Vagrant is to have an equal development environment as the production environment. Therefore it would be nice to be able to choose between MySQL and MariaDB. Could this be 

But with some personal provisioning of the machine each user should be able to mirror his production environment, right? 

I haven't used [PuPHPet](https://puphpet.com), but that seems like a easy to use way to configure a box. Could PuPHPet be implemented, or used as an inspiration? As I said: I have never used it, so  I might have misunderstood how it works.

**Comment by mikeschinkel** [comment]
> _After reading your quotes I think that I would like to start to use MariaDB._

@nonameolsson Cool. Next step on our end is for @clubdeuce and I to discuss if we should:

1.) Upgrade to MySQL 5.6 in short term
2.) Switch to MariaDB in short term
3.) Install both and allow the user to switch them out short term.

> _I do think the suggestion of some kind of "Package Installation" would be balanced way to continue offering a good Vagrant machine for WordPress-development._

Glad you like the idea. I am very excited about this prospect, but its going to take a little R&D to figure out the best way to pull it off and make it easy.

> _I think that one of the biggest advantages of using Vagrant is to have an equal development environment as the production environment._

I have thought that too, but I have spoken to many people who thus far don't actually do that and they say it generally works fine for them.  I think the stack required for WordPress is so standardized and the alternatives are so compatible that I think for WordPress it is not as critical for SaaS companies building a custom stack using Ruby/Gems/Node/MongoDB/Angular/etc.etc.

Still, we ultimately do want to get to the point we can allow people to set up a mostly identical environment for deployment.

> But with some personal *provisioning* of the machine...

Bold is mine ^^^; so I want to make some points about our philosophy vs. that of VVV, Trellis, VIP Quickstart, etc. and of Vagrant in general.

Vagrant is great in that it allows people to build whatever stack they need.  But it really leverages a _*provisioner*_ such as Ansible, Puppet, Chef or Salt.  This lets someone woth sysadmin skills build out a script that can automatically build a stack rather than require a sysadmin to get involved every time an existing configuration is needed for a new machine.  Basically: Devops.

However *_in my opinion_* provisioners are problematic because they were designed to solve an incredibly complex problem such as keeping 1000 servers correctly configured and in sync given practically an infinite potential number of configurations.  And because the scope of the problem is so large these tools are not perfect. And when they break, you need sysadmin skills to diagnose the problem and fix it.  Especially when using `apt-get` that can potentially pull down new versions of software that might be subtly incompatible with the last time someone ran the same apt-get.

But for WordPress the number of potential configurations is finite and small and the number of OSes we need to support on WPLib Box is currently one (1).  Since our goal is to build a _"product"_ that meets your needs vs. provide you with a Vagrant script that may or may not meet your needs we want that product to _"just work"_, as Steve Jobs often said of Apple products.  So we think if we can have our own package manager specifically for the box we can greatly reduce the chance that something breaks and you have to try to fix it.

Plus not only do they break during build often enough to totally screw up an entire day when a developer is at deadline and the client does not understand why, the provisioners are *SLOW*, *SLOW*, *SLOW*!  VVV can take 30 minutes to provision a box. WPLib Box is provisioned in under 1 minute.

> _I haven't used PuPHPet, but that seems like a easy to use way to configure a box. Could PuPHPet be implemented, or used as an inspiration?_

Actually, PuPHPet just asks you for your desired configuration and then generates a set of [Puppet](https://puppet.com/) scripts for provisioning that work with the `Vagrantfile` that it generates too.  For each configuration you need to generate a different set of scripts and then run through all the 30-60 minutes of provisioning that is similar to what you get with VVV. But, if there is any incompatibility in the scripts you generate then it is up to you to debug it, and it is up to you to learn Puppet to add any features you might want.

BTW, I tried to learn Puppet.  After about 2 weeks I realized I would need to work with it for about 3-6 months before I felt I would be productive with it.  And unless you are a devops or a sysadmin or are highly motivated to learn things you don't need to learn when you could be learning other things that benefit your development, I really don't think it makes sense to learn Puppet if all you really want to do is deliver WordPress solutions to clients.

Don't get me wrong, PuPHPet is a great tool, and was especially awesome when all of this was new. But after working with it and VVV the novelty wore off for me to have to know Puppet just to be able to work in WordPress.

FYI, we use Ansible to build our WPLib Box image, but I don't do that someone else has that expertise, not me.

> _an easy to use way to configure a box._

Which leaves the unanswered question, how will we do it? 

Short term we are going to do our best to allow things to coexist, like PHP 5.6 and PHP 7.0.  But that won't scale in complexity.  

Our plan it to move to a Container-based environment where everything is in a container and mixing and matching Containers is how we will allow people to configure their own stack because containers generally don't create conflicts with other contains unless they are on the same internal IP address and port number.  Which is -- relatively speaking -- much easier to manage than software that needs to be installed into the same directory space.
