### ISSUE TITLE
Disassociating git repository

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#157]
I am looking at the code for the command to disassociate the WPlLib box repository. Frankly, I do not know enough BASH to understand it. Therefore, let me present a situation and you tell me what will happen in this case:

- I am starting a new project, so I clone the `wplib-box` repository.
- I do a `vagrant up`.
- I begin coding my project, committing to my project's repository.
- Two weeks later, an updated version of the box image is released. I want to update.
- I do a `vagrant destroy`, `vagrant box update`, and `vagrant up`.

What happens to my git configuration?

**Comment by clubdeuce** [comment]
And to follow up, how will those working on the `wplib-box` project itself continue to do so when a `vagrant up` removes the git information for the `wplib-box` repository?

**Comment by mikeschinkel** [comment]
@clubdeuce 

> _What happens to my git configuration?_

Unless there is a bug [in the code](https://github.com/wplib/box-scripts/blob/master/guest/cli/commands/disassociate-git-repo), nothing happens other than the new box image is downloaded and used.

> _how will those working on the wplib-box project itself continue to do so when a vagrant up removes the git information for the wplib-box repository?_

For those people, they would [*reassociate the Git repo*](https://github.com/wplib/box-scripts/blob/master/guest/cli/commands/reassociate-git-repo) before they attempt to commit changes to Git:

    vagrant ssh
    box reassociate-git-repo

Note that once we move to a single install of WPLib Box and have it point to a sites directory _(or multiple site directories?)_ to find WordPress projects these commands become no longer needed. The reason it is needed is because our current Git repo clones into what should become the user's project repo _(referencing our conversation on Monday, this is another reason why the workflow of cloning WPLib Box to create a new project is problematic.)_

**Comment by clubdeuce** [comment]
If we were to tell people to install the box using `composer create-project`, the commands are also no longer needed.

**Comment by mikeschinkel** [comment]
@clubdeuce Except that adds back in the requirement to have `composer` installed prior to getting the box to work.

I think the better solution is simply to move forward with a multi-project box as our next release. Do you see any reason what that is not a viable resolution?

**Comment by clubdeuce** [comment]
The user will still have to get WPLib-Box in some way initially. I do not see where having the ability to be multi-project or not affects this.

The [installer](https://github.com/wplib/wplib-box/issues/154) is what truly removes this necessity, as I understand it.

**Comment by mikeschinkel** [comment]
> The user will still have to get WPLib-Box in some way initially. I do not see where having the ability to be multi-project or not affects this.

But they won't be working on their own code inside of the cloned WPLib Box repository.  That is what created the need for this command for me, and once the user no longer works inside of the same directory as `Vagrantfile`, or any its subdirectories, then we can remove these commands.
