### ISSUE TITLE
WordPress version is 4.5

### ISSUE THREAD

**Issue by Shelob9** [wplib/wplib-box#177]

**Comment by mikeschinkel** [comment]
Yeah, we need to update.  

It is kind of a thankless task since it is so easy for the user of WPLib Box to update using WordPress auto-updater, which is why we have not made sure to stay on top of it.  We are working on the next major version which should have much better way to stay current.

Anyway, thanks for using WPLib Box.  I will tackle this soon.

**Comment by Shelob9** [comment]
@mikeschinkel My PR sets value in composer to 4.7.2.  Wondering if `*` or latest 4.7 (`4.7.^` I think) would be better?

**Comment by mikeschinkel** [comment]
Shelob9 - Yes, almost certainly.

But realize we also include an installed copy of WordPress in this repo so that the person who clones this will have fewer steps to get to a successful installation.  And many people who are evaluating it do not use composer.  

So it that which I was thinking about and not the composer use-case, the latter of which is an easier problem to tackle.

**Comment by mikeschinkel** [comment]
BTW, I did not recognize @Shelob9 so did not realize who I was chatting with.  :-)

**Comment by clubdeuce** [comment]
@mikeschinkel This is completed, yes?
