### ISSUE TITLE
Bad Gateway while trying to use PHP 7.1.

### ISSUE THREAD

**Issue by baselbers** [wplib/wplib-box#243]
I've installed PHP 7.1 and switched PHP version with below method, but I get Bad Gateway when accessing site. No errors in nginx error log.  I've checked permission. What am I missing? I know it is not much info, so tell me what info you need. :)
https://github.com/wplib/wplib-box/blob/master/FAQ.md#switch-php

**Comment by mikeschinkel** [comment]
Hi @baselbers -  I feel awful that we didn't follow up on this until now, especially since it was a documentation issue.

That section you mention is obsolete.  I have updated it and the [**new instructions**](https://github.com/wplib/wplib-box/blob/master/FAQ.md#switch-php) should work for you as I just verified them with version `0.15.0`.  Please try and let us know.  _(You may want to do a `vagrant destroy` and `vagrant up` again to ensure your changes did not break anything.  

Also make sure you have the latest release by running `vagrant box update` in the directory where you have `Vagrantfile`, and make sure you either do not have a line like the following in your `Vagrantfile`, or that it is set to `0.15.0` _(that is the latest box release):_

    config.vm.box_version = "0.15.0"

**Comment by baselbers** [comment]
Hi @mikeschinkel thanks for your quick reply.

I've updated box from 0.11 to 0.15. Did a `vagrant destroy` and `vagrant up` and followed the new instructions, but I get following message when using `box set-processvm-php7.1` command.

> jq: error: Could not open file /vagrant/project.json: No such file or directory

**Comment by mikeschinkel** [comment]
@baselbers Guess we still have some debugging to do.  Can you grab a copy of `project.json` from this repo and put in the same directory as your `Vagrantfile`, then try `Vagrant reload or `vagrant up`?
