### ISSUE TITLE
Only include default services in box image?

### ISSUE THREAD

**Issue by clubdeuce** [wplib/wplib-box#247]
Our recent changes to the box have caused the size of the box image to grow substantially. As a result I propose we only include the default services and move optional services into installable packages. This would reduce the box image size by ~500MB.

Defaults:

+ Nginx
+ MySQL
+ PHP 7.0 _(and 7.1 as it is not yet a docker container)_
+ Redis

Installable Packages:

+ MariaDB
+ Memcached
+ PHP 5.6

**Comment by mikeschinkel** [comment]
Agreed, especially because we need to be able to have installable packages identifiable and downloadable automatically when setting up a project.

Also I wonder if we should even include Redis by default?

**Comment by mikeschinkel** [comment]
Revisiting this, I would like to have @MickMakes weight in.  

I'd also like to ensure we have our a plan to ensure that changing stack does not break the box anything because of failed downloads, and if a download fails it should be made completely clear to the user what happened and why so they can easily correct the problem.

**Comment by mikeschinkel** [comment]
@MickMakes For your review
