### ISSUE TITLE
504 Gateway Time-out  nginx/1.11.10

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#252]
I am getting these on `0.15.0` after about 30 seconds, or maybe longer.  Did you ensure the proxy had a long timeout?

**Comment by clubdeuce** [comment]
@mikeschinkel  I did. Here is the configuration file for the nginx proxy:

````
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        off;
    client_max_body_size 100M;
    fastcgi_read_timeout 9999;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
````

**Comment by clubdeuce** [comment]
@mikeschinkel The cause of this issue is the missing `proxy_read_timeout` directive in the default virtual host configuration. If not specified, this value defaults to sixty seconds.

You can update your current installation using the following:

`docker stop proxy && docker rm proxy && docker run -d -p 80:80 -p 443:443 --name proxy -v /srv/sites:/srv/sites --network wplibbox --restart=always wplib/proxy:0.15.1`

**Comment by mikeschinkel** [comment]
@clubdeuce AWESOME work!
