### ISSUE TITLE
Cannot upload images or write to uploads directory

### ISSUE THREAD

**Issue by mikeschinkel** [wplib/wplib-box#254]

**Comment by clubdeuce** [comment]
@mikeschinkel This has been resolved. In order to apply the necessary updates, you can do the following _(assuming you are using PHP 7.0)_:

`docker stop php7_fpm && docker rm php7_fpm && docker pull wplib/php-fpm:7.0.16 && docker create -p 9000:9000 --name php7_fpm -v /var/www:/var/www -v /srv/sites:/srv/sites --network wplibbox wplib/php-fpm:7.0.16`

For PHP 5.6:

`docker stop php5_fpm &&  docker rm php5_fpm && docker pull wplib/php-fpm:5.6.30 && docker create -p 9000:9000 --name php5_fpm -v /var/www:/var/www -v /srv/sites:/srv/sites --network wplibbox wplib/php-fpm:5.6.30`

**Comment by clubdeuce** [comment]
This will be a non-issue in `0.16.0`
