### ISSUE TITLE
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect

### ISSUE THREAD

**Issue by przemekcichon** [wplib/wplib-box#260]
Hi Team,

First of all, this is a really great tool. I have tried WPLib Box today for the first time and it seems to be very easy to use. However, I did encounter few issues so far. I have a fresh out of the box installation. The only thing I have changed was upgrading WP Core via the composer update command. The problem is that after a vagrant halt I get this message in the `sql/current.sql` file:
> mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect

After logging into the vagrant server I don't see `mysqld` in the `/var/run/` directory. 

If I read the results of ps aux correctly the `mysql` server is running? But I don't know what is the location of mysqld.sock file.
```bash
vagrant@loc:~$ ps aux | grep mysql
vboxadd   1887  0.0 36.9 1122992 184960 ?      Ssl  20:49   0:01 mysqld
vagrant   3135  0.0  0.4  14132  2296 pts/1    S+   21:19   0:00 grep --color=auto mysql
```

Please let me know if I should add anything else here.

Thanks,
Przemek

**Comment by mikeschinkel** [comment]
Hi @przemekcichon - We are painfully aware of this issue and plan to fix for `0.16.0` In the near term the best option is to use our most-rock solid version `0.11.2` instead.  To do so add this to your `Vagrantfile` and run `vagrant reload`:

    config.vm.box_version = "0.11.2"

If you have not backed up your database first run `vagrant ssh` then `box backup-db` which will create a `current.sql` file in `/sql/`.  

Now run `vagrant reload` and then `vagrant ssh`.  Change to `/vagrant/sql` and renamed `current.sql` to another filename, like `export.sql` then run `box import-db export.sql`. That should get you up and working.

-------------
Why the problems with `0.15.0`?  As part of our longer term plan we have been moving to using Docker to allow for mix-and-match web server, database server, etc.  Unfortunately we did not realize the extent of usability issues moving to Docker containers would cause until recently, so we are working to resolve those issues, and we hope to solve most of them by our next release, `0.16.0`.  

Normally we have 3 week cycles but because of a client requirement this release is probably going to take several more weeks at least before it can see the light of day.

**Comment by clubdeuce** [comment]
@przemekcichon @mikeschinkel Unfortunately, the `vagrant reload` will _*not*_ create a new version of the box based upon the newly specified box image version. After specifying the `config.vm.box_version`, you will have to do a `vagrant destroy` and then `vagrant up`. Of course, the database backup is still necessary.

**Comment by clubdeuce** [comment]
@przemekcichon The MySQL server is indeed running, however it is in a Docker container. As a result, there is no sock file present on the virtual machine.

That being said, I am unable to replicate this issue.

**Comment by mikeschinkel** [comment]
@clubdeuce In your testing did you run a WP Core via the composer update command prior to testing `vagrant halt`?  

@przemekcichon is there a possibility that you did something because you assumed MySQL was installed directly onto Ubuntu rather than via Containers?

**Comment by clubdeuce** [comment]
@mikeschinkel I did.

**Comment by mikeschinkel** [comment]
Since we've had not feedback from the OP I'm closing this.  Feel free to reopen if anyone can provide more information.
