### ISSUE TITLE
Add pre and after provision script to Vagrantfile

### ISSUE THREAD

**Issue by andreasnrb** [wplib/wplib-box#66]
It will be beneficial to have a script that runs after provisioning in case you want to do some VM specific manipulations. VVV has pre and post provision in their setup and I have made use of post provision for file manipulations in the VM. Thats what I usually do instead of rsync that I tried and posted about in #63.

**Comment by mikeschinkel** [comment]
Given how our box works, do we need a post provision script vs. just adding to the end of `provision.sh`?  Help me understand what should work here.

**Comment by andreasnrb** [comment]
I think its better that we limit the need for any changes to core files. Then its easier to just update to latest box files and no need to merge, or copy paste.

**Comment by mikeschinkel** [comment]
@andreasnrb So optional before and after scripts that we ourselves do not touch?

**Comment by andreasnrb** [comment]
@mikeschinkel exactly.

**Comment by mikeschinkel** [comment]
@andreasnrb: Take a look at the “with-hooks” branch and let me know what you think.

**Comment by andreasnrb** [comment]
Can't use system in this case since its run on the host and not in the VM.
It needs to be something like this.
```
  if File.exists?(File.join(vagrant_dir,'custom','after-provision.sh')) then
    config.vm.provision :shell, :path => File.join( "custom", "after-provision.sh" )
  end
```

**Comment by mikeschinkel** [comment]
@andreasnrb That kind of syntax would really complicate our `Vagrantfile` and that goes counter to our primary goal of keeping things simple and easy to understand. 

And part of Vagrant's philosophy coming from Mitchell himself it everything should be declarative. 

So I think the way to address that is with a custom Vagrant plugin.

That said, there is no reason you can't modify the `Vagrantfile` yourself  as we very much are not viewing it as part of the box but instead as the initial working example for how to use the box.

**Comment by andreasnrb** [comment]
K developers will probably expect to be able to manipulate things easily without having to fork the project and merge from upstream etc. Which is the current method.

**Comment by mikeschinkel** [comment]
This project is really **just** an entry point, designed to provide a quick start 

We do not intend for people to clone this repo more than the first time, I.e. just when they are getting started.  Actually I would love to deprecate the repo and just provide an installer, but that would be down the road if at all.

Once we have a CLI we will recommend developers use the CLI to generate their own project's initial Vagrantfile and then maintain the Vagrantfile as a file that is owned by their project and not a file that is owned by our project.

It has become clear to me for this vision to work we will need to build and offer a Vagrant plugin to manage the details so that the Vangrantfile becomes very simple.

**Comment by mikeschinkel** [comment]
Of course during the beta phase these things won't all be so smooth...

**Comment by andreasnrb** [comment]
I'll just add it to my generator then my needs are satisfied.

2016-05-01 20:46 GMT+02:00 Mike Schinkel <notifications@github.com>:

**Comment by mikeschinkel** [comment]
Thanks
